# Generated by Django 2.2.4 on 2023-02-01 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('hall', models.CharField(max_length=3)),
                ('kitchen', models.CharField(max_length=3)),
                ('balcony', models.CharField(max_length=3)),
                ('bedrooms', models.IntegerField()),
                ('AC', models.CharField(max_length=3)),
                ('img', models.ImageField(upload_to='files/apartments/')),
                ('desc', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Chalet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('hall', models.CharField(max_length=3)),
                ('kitchen', models.CharField(max_length=3)),
                ('balcony', models.CharField(max_length=3)),
                ('bedrooms', models.IntegerField()),
                ('AC', models.CharField(max_length=3)),
                ('pool', models.CharField(max_length=3)),
                ('desc', models.CharField(max_length=200)),
                ('img', models.ImageField(upload_to='files/chalet/')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('phone_number', models.IntegerField()),
                ('password', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sakanatapp_app.Apartment')),
                ('chalet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sakanatapp_app.Chalet')),
            ],
        ),
        migrations.AddField(
            model_name='chalet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chalets', to='sakanatapp_app.User'),
        ),
        migrations.AddField(
            model_name='apartment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartments', to='sakanatapp_app.User'),
        ),
    ]
